# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Content
    url: /content/
    weight: 3
  - name: Assignments
    url: /assignment/
    weight: 4
  - name: Labs
    url: /lab/
    weight: 5    
  - name: Resources
    url: /resource/
    weight: 6
  - name: '<i class="fab fa-slack"></i>'
    url: "https://dsba6010-spring2022.slack.com"
    weight: 7

content:
  - name: Overview
    weight: 1
  - name: Course content
    weight: 2
example:
  - name: Labs
    weight: 1
assignment:
  - name: Assignments
    weight: 1
  - name: Problem sets
    weight: 2
  - name: Project
    weight: 3
resource:
  - name: Overview
    weight: 1
  - name: Guides
    weight: 2
  - name: Resources
    weight: 3
  - name: Study guides
    weight: 4
