# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: custom
day_night: true
# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font: 'Native'
font_size: L

# SEO

site_type: Course
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# Contact (edit or remove options as required)

contact_links:
  - icon: comments
    icon_pack: fas
    name: Discuss on the forum
    link: 'https://github.com/wowchemy/wowchemy-hugo-modules/discussions'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
highlight_languages: 
  - r
math: true
diagram: false
privacy_pack: false
edit_page:
  repo_url: 'github.com/wesslen/dsba6010-spring2022'
  content_dir: ''
  repo_branch: main
  editable:
    docs: true
    page: false
    post: false
show_related:
  docs: false
  page: false
  post: false
  project: false
  publication: false
  talk: false
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
############################
## Content Management System
############################
cms:
  # See https://sourcethemes.com/academic/docs/install/#install-with-web-browser
  netlify_cms: true
icon:
  pack:
    ai: false
    
    

author: Ryan Wesslen

instructor: 
  name: Dr. Ryan Wesslen
  email: rwesslen@uncc.edu
  url: "https://wesslen.netlify.app"
  twitter: ryanwesslen
  github: wesslen
  office: "Center City 714"
  contact_policy: >-
    E-mail and Slack are the best ways to get in contact with me.
  appointment_url: "https://calendly.com/ryanwesslen/bayesian-stats-office-hours"
course:
  number: "DSBA 6010 / STAT 7027"
  semester: "Spring 2022"
  days: "Monday"
  time: "12:00pm-2:45pm"
  location: "Center City 1101"
  dates: "Jan 10, 2022 - May 12, 2022"
  github: "wesslen/dsba6010-spring2022"
  copyrightYear: "2022"
  slack: "https://dsba6010-spring2022.slack.com"

university: 
  name: University of North Carolina at Charlotte
  url: "https://www.uncc.edu"

school:
  name: School of Data Science
  url: "https://datascience.charlotte.edu/"

############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/media/` folder and specify image name here.
sharing_image: "dsba6010-hex.png"

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter: "ryanwesslen"
