# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Bayesian Statistics # Website name
baseurl: 'https://dsba6010-spring2022.netlify.app' # Website URL
#copyright: '© 2021 Ryan Wesslen' # Footer text, e.g. '© {year} Me'

############################
## LANGUAGE
############################


############################
## MODULES
############################

############################
## ADVANCED
############################

# ------------------
# Building options
# ------------------
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: yes

ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.Rproj.user$
  - \.Rhistory$
  - \.knit\.md$
  - \.utf8\.md$

# No taxonomy
disableKinds:
  - taxonomy
  - taxonomyTerm

imaging:
  anchor: smart
  quality: 75
  resampleFilter: lanczos

# Markdown options
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    style: "monokai"
  tableOfContents:
    startLevel: 2
    endLevel: 4
footnotereturnlinkcontents: <sup>^</sup>

defaultContentLanguage: en
copyright: ''
enableGitInfo: no
hasCJKLanguage: no
defaultContentLanguageInSubdir: no
removePathAccents: yes
summaryLength: 30
paginate: 10
enableEmoji: yes


# ----------------
# Output options
# ----------------
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes: webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
enableRobotsTXT: yes

taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
  
  
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy
