---
title: Assignment details
menu:
  assignment:
    parent: Assignments
    weight: 1
type: docs
---

The main goals of this class are to help you design, critique, code, and run Bayesian statistical models. Each type of assignment in this class is designed to help you achieve one or more of these goals.

## Problem sets

To practice writing code, running inferential models, and thinking about causation, you will complete a series of problem sets. 

You need to show that you made a good faith effort to work each question. I will not grade these in detail. The problem sets will be graded using a check system:

- ✔++: (*110% in gradebook*) Assignment is 100% completed. Every question was attempted and answered, and most answers are correct. Document is clean and easy to follow. Work is exceptional. I will not assign these often.
- ✔+: (*100% in gradebook*) Assignment is complete and most answers are correct. **This is the expected level of performance.**
- ✔: (*90% in gradebook*) Completed most of the assignment and answers are mostly correct. 
- ✔−: (*75% in gradebook*) Assignment is above 50% correct but several answers or approaches are incorrect. This indicates that you need to improve next time. I will hopefully not assign these often.
- ✔−−: (*50% in gradebook*) Major components were not completed and/or less than 50% of questions were correct.

Zeros will be issued for problem sets not completed.

You may (and should!) work together on the problem sets, but *you must turn in your own answers.* You cannot work in groups of more than **two** people, and you must note who participated in the group in your assignment.

## Exam

There will be **one exam** in the course that covers most lectures materials. 

The exam will be:

* in-class, paper, and without notes; 

* largely consist of lecture check-in questions, lecture/chapter readings, and problem sets;

* multiple choice questions with short answer questions.

The exam will be on **April 18, 2022**. Make-up exams will only be permissible through excused absences require doctor's note or instructor's permission. If you know you have a conflict, let me know at least one week in advance (hopefully, more time).

If situations require us to work remotely, the exam may have changes in its structure.

## Final project

At the end of the course, you will demonstrate your knowledge of Bayesian statistics and causal inference by completing a final project.

There is no final exam. The final project is your final exam. [Details for the final project.](/assignment/final-project/)

### Scope

Projects can cover anything related to Bayesian inference. We'll cover a range of applications in Bayesian inference for [check-in assigment 1](/assignment/01-project/) and students are encouraged to think outside of the box. As mentioned in the syllabus, students may use programming language outside of R/Stan for this project (e.g., Turing.jl, PyMC).

### Check-in assigments

For your [final project](/assignment/final-project/), you will have two check-in projects. 
The first check-in is an [in-class presentation](/assignment/01-project/) on February 14th. Presentations will be done individually and can be 5-10 minutes long. Students may present in class or digitally (e.g., .mp4 video). If students choose to upload digitally, the document must be submitted at 11:59am of February 14th.

The second check-in will be a [project proposal](/assignment/02-project/) due on March 28th. This will need to be turned in on Canvas. 

Similar to problem sets, late assignments (within 48 hours) will be subject to a 50% reduction. Assignments received over 48 hours will be subject to a zero grade. 

Each check-in will make up 5% of your Final Project grade (so 1.5% of your final grade) and these assignments will be graded using a check system:

- ✔++: (*110% in gradebook*) Document/presentation is clear, concise, and thoughtful. Document/Presentation exceeded all requirements and ideas are extremely novel. I will not assign these often.
- ✔+: (*100% in gradebook*) Document/presentation is easy to follow and the work fulfilled the requirements. **This is the expected level of performance.**
- ✔: (*90% in gradebook*) Document/presentation was appropriate but gaps in presentation, explanation, or details. Easy fixes that came be improved upon next time.
- ✔−: (*75% in gradebook*) Document/presentation had several problems. Feedback will be provided and student should work to improve next time. 
- ✔−−: (*50% in gradebook*) Document/presentation missed major requirements and demonstrates a lack of planning and preparation. I will hopefully not assign these.